# Generated by Django 4.0.6 on 2022-07-07 17:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveySent',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, editable=False, max_length=320, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='survey.survey')),
            ],
            options={
                'db_table': 'survey_sent',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
            options={
                'db_table': 'submissions',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_numeric', models.FloatField(blank=True, null=True)),
                ('content_character', models.TextField(blank=True, null=True)),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='survey.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='survey.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='answer.submission')),
            ],
            options={
                'db_table': 'answers',
            },
        ),
    ]
